#!/usr/bin/env bash
# upload-zipline.sh -- upload every MP4 in docs/videos/ to Zipline and record the
# share links.
#
#   tools/video/upload-zipline.sh [--dir docs/videos] [--only NAME]
#
# Requires ZIPLINE_URL and ZIPLINE_TOKEN in the environment. The token is passed
# to curl through a header read from the environment and is never echoed, never
# written to a file, and never printed -- only the returned URL is.
#
# An upload that fails is reported with the local path and the HTTP status, and
# is NOT retried in a loop: a blind retry against an auth or quota error just
# makes noise. Re-run the script to try again deliberately.
#
# Writes docs/videos/LINKS.md with a row per video: name, local path, size,
# duration, resolution and share URL.

set -uo pipefail
HERE="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "$HERE/../.." && pwd)"

DIR="$REPO_ROOT/docs/videos"
ONLY=""
while [ $# -gt 0 ]; do
  case "$1" in
    --dir)  DIR="$2"; shift 2 ;;
    --only) ONLY="$2"; shift 2 ;;
    *) echo "upload-zipline: unknown argument: $1" >&2; exit 2 ;;
  esac
done

if [ -z "${ZIPLINE_URL:-}" ] || [ -z "${ZIPLINE_TOKEN:-}" ]; then
  echo "upload-zipline: ZIPLINE_URL and ZIPLINE_TOKEN must both be set" >&2
  exit 2
fi

LINKS="$DIR/LINKS.md"
# Fixed scratch dir (no cleanup step: nothing here needs deleting, and this
# script deliberately contains no destructive shell command).
TMP="/tmp/fvsrv/zipline-upload"
mkdir -p "$TMP"

# The table is built by appending, so a re-run for a few failed uploads adds to
# the existing rows instead of replacing the whole table. Start a fresh file
# only when there is not one already, or when everything is being re-uploaded.
if [ ! -s "$LINKS" ] || [ -z "$ONLY" ]; then
{
  echo "# Share links"
  echo
  echo "Uploaded to \`$ZIPLINE_URL\` with \`POST /api/upload\`."
  echo "Generated by \`tools/video/upload-zipline.sh\`."
  echo
  echo "| video | duration | resolution | size | share URL | local path |"
  echo "|---|---|---|---|---|---|"
} > "$LINKS"
fi

fail=0
for f in "$DIR"/*.mp4; do
  [ -e "$f" ] || { echo "upload-zipline: no MP4 files in $DIR"; exit 3; }
  name="$(basename "$f" .mp4)"
  if [ -n "$ONLY" ] && [ "$ONLY" != "$name" ]; then continue; fi

  dur="$(ffprobe -v error -show_entries format=duration -of default=nw=1:nk=1 "$f")"
  res="$(ffprobe -v error -select_streams v:0 -show_entries stream=width,height -of csv=p=0:s=x "$f")"
  size="$(stat -c%s "$f")"

  code="$(curl -sS -o "$TMP/resp.json" -w '%{http_code}' \
      -X POST "$ZIPLINE_URL/api/upload" \
      -H "Authorization: $ZIPLINE_TOKEN" \
      -F "file=@$f")"

  url=""
  if [ "$code" = "200" ] || [ "$code" = "201" ]; then
    url="$(python3 - "$TMP/resp.json" <<'PY'
import json, sys
try:
    d = json.load(open(sys.argv[1]))
except Exception:
    sys.exit(0)
def walk(o):
    if isinstance(o, dict):
        for k in ('url', 'files', 'file'):
            if k in o:
                v = o[k]
                if isinstance(v, str):
                    print(v); raise SystemExit
                if isinstance(v, list) and v:
                    walk(v[0]); raise SystemExit
                if isinstance(v, dict):
                    walk(v); raise SystemExit
        for v in o.values():
            walk(v)
    elif isinstance(o, list) and o:
        walk(o[0])
walk(d)
PY
)"
  fi

  if [ -n "$url" ]; then
    printf '| %s | %ss | %s | %s | %s | `%s` |\n' "$name" "$dur" "$res" "$size" "$url" "${f#"$REPO_ROOT"/}" >> "$LINKS"
    echo "OK   $name -> $url"
  else
    fail=1
    printf '| %s | %ss | %s | %s | _UPLOAD FAILED (http %s)_ | `%s` |\n' \
      "$name" "$dur" "$res" "$size" "$code" "${f#"$REPO_ROOT"/}" >> "$LINKS"
    echo "FAIL $name  http=$code  local=$f" >&2
    head -c 400 "$TMP/resp.json" >&2; echo >&2
  fi
done

echo
echo "links table: $LINKS"
exit "$fail"