//! Neural-I/O groups from the pinned MaleCNS artifact.
//!
//! `assets/neuromechfly/male_cns_v1_neural_io.json` selects annotated
//! populations by cell type from Janelia's own annotation table. Every group
//! resolves to real MaleCNS body IDs, all of which are present in the pack
//! (the artifact reports zero missing roots). Nothing here is fabricated
//! wiring: these are the published motor neurons, descending neurons and
//! sensory receptor populations, used as explicit readout and stimulation
//! interfaces.

use crate::lif::DT_MS;
use crate::pack::Connectome;
use anyhow::{Context, Result};
use serde_json::Value;
use std::collections::HashMap;
use std::path::{Path, PathBuf};

/// Neuron-group annotations shipped with the repo (from the MaleCNS /
/// neuromechanistic-fly release). Override with `FLYVERSE_IO_JSON`.
pub const IO_JSON: &str = "assets/male_cns_v1_neural_io.json";

/// Resolve the group annotation table: `$FLYVERSE_IO_JSON`, else IO_JSON.
pub fn io_json_path() -> PathBuf {
    std::env::var("FLYVERSE_IO_JSON")
        .map(PathBuf::from)
        .unwrap_or_else(|_| PathBuf::from(IO_JSON))
}

/// Physiological full scale of a flight POWER motor neuron's firing rate,
/// Hz per neuron.
///
/// The flight power muscles (DLM/DVM) are *asynchronous* indirect flight
/// muscles: the wingbeat is generated by the thorax's own stretch-activated
/// oscillator at ~200 Hz and is decoupled from the motor-neuron firing rate,
/// which only sets the muscle's activation level. The consequence is that the
/// motor neurons fire far BELOW the wingbeat frequency:
///
/// * Gordon & Dickinson (2006), PNAS 103(11):4311-4315,
///   doi:10.1073/pnas.0510109103: "The motor neurons of the A-IFMs fire at a
///   rate (approximately 5 Hz in *Drosophila*) well below contraction frequency
///   (approximately 200 Hz)"; mechanical power rises and falls with the firing
///   frequency, and the recorded spike frequency went "up to approximately
///   20 Hz" during visually elicited manoeuvres (2-fold change in power per
///   3-fold change in rate).
/// * Lehmann, Skandalis & Berthe (2013), J. R. Soc. Interface 10:20121050,
///   doi:10.1098/rsif.2012.1050, and Lehmann & Bartussek (2016), J. Comp.
///   Physiol. A 202, doi:10.1007/s00359-016-1133-9: "the A-IFM's low spike
///   frequency between 5 and 20 Hz maintains rather constant intramuscular
///   calcium levels during flight"; power is linear in intramuscular calcium
///   (R^2 ~ 0.95) over 20-120 W/kg at 56-79 nM.
/// * "Gap junctions desynchronize a neural circuit to stabilize insect
///   flight", Nature 618:118-124 (2023), doi:10.1038/s41586-023-06099-0: each
///   of the five identified DLM motor neurons "fires only every approximately
///   20th to 40th wingbeat" (5-10 Hz at a 200 Hz wingbeat); the tethered-flight
///   working range is "approximately 3-12 Hz" and the f-I curve is linear over
///   3-30 Hz, i.e. tuned to that range.
///
/// So the actuator's full scale -- the rate at which a flight power muscle is
/// maximally activated and the wing gives full stroke amplitude -- is **20 Hz**
/// per neuron, not the rate a spike-count window can arithmetically express.
pub const POWER_MN_MAX_HZ: f32 = 20.0;

/// The physiological full scale of a read-out, Hz per neuron, or `None` when
/// the group has no physiological anchor.
///
/// `None` groups keep the window's arithmetic ceiling as their reference, which
/// at least leaves the read-out a fraction of the pool in 0..1. Only the
/// flight-power pools are anchored so far: they are the ones that drive an
/// actuator (`body.rs` reads them as the muscle activation `a`), so their scale
/// decides whether the fly can fly, and 500 Hz of motor drive is not a physical
/// quantity a muscle can be asked for. See `POWER_MN_MAX_HZ`.
pub fn phys_full_scale_hz(name: &str) -> Option<f32> {
    match name {
        "motor_flight_power_left" | "motor_flight_power_right" => Some(POWER_MN_MAX_HZ),
        _ => None,
    }
}

/// Region buckets used by the HUD. Order is the wire order.
pub const REGION_NAMES: [&str; 12] = [
    "sensory_leg",
    "olfaction",
    "taste",
    "visual_motion",
    "visual_loom",
    "flight_descending",
    "flight_motor",
    "walking_motor",
    "landing_motor",
    "feeding_motor",
    "central",
    "other",
];

fn region_of(group: &str) -> u8 {
    match group {
        "olfaction_left" | "olfaction_right" => 1,
        "taste_sugar" => 2,
        "visual_motion_left" | "visual_motion_right" => 3,
        "visual_loom_left" | "visual_loom_right" => 4,
        "flight_dng02_left" | "flight_dng02_right" | "flight_dng07_left"
        | "flight_dng07_right" | "flight_state_sapp_left" | "flight_state_sapp_right"
        | "flight_steering_dn_left" | "flight_steering_dn_right" => 5,
        "motor_flight_power_left" | "motor_flight_power_right" | "motor_flight_steering_left"
        | "motor_flight_steering_right" => 6,
        "motor_walking_left" | "motor_walking_right" | "walking_dn_left" | "walking_dn_right" => 7,
        "motor_landing_left" | "motor_landing_right" | "landing_dn_left" | "landing_dn_right" => 8,
        "feeding_mn9" => 9,
        _ => 11,
    }
}

pub struct Groups {
    pub names: Vec<String>,
    pub members: Vec<Vec<u32>>,
    /// name -> group index
    pub by_name: HashMap<String, usize>,
    /// neuron -> group index + 1 (0 means the neuron is in no group)
    pub neuron_group: Vec<u16>,
    /// group -> region bucket
    pub group_region: Vec<u8>,
    /// group -> normalising divisor (member count, at least 1)
    pub group_size: Vec<u32>,
    /// group -> physiological full scale in Hz per neuron, or 0.0 when the group
    /// has no physiological anchor and the window's arithmetic ceiling is used
    /// instead. See `phys_full_scale_hz`.
    pub group_scale_hz: Vec<f32>,
    /// food-odour channels: (glomerulus, attractive?, member indices)
    pub odor_channels: Vec<(String, bool, Vec<u32>)>,
}

impl Groups {
    pub fn get(&self, name: &str) -> &[u32] {
        match self.by_name.get(name) {
            Some(&i) => &self.members[i],
            None => &[],
        }
    }

    pub fn idx(&self, name: &str) -> usize {
        *self.by_name.get(name).unwrap_or(&usize::MAX)
    }

    pub fn load(c: &Connectome, path: &Path) -> Result<Groups> {
        let text = std::fs::read_to_string(path)
            .with_context(|| format!("read {}", path.display()))?;
        let root: Value = serde_json::from_str(&text)?;

        let mut names = Vec::new();
        let mut members: Vec<Vec<u32>> = Vec::new();
        let mut by_name = HashMap::new();

        let groups = root
            .get("groups")
            .and_then(|v| v.as_object())
            .context("neural_io has no groups object")?;
        let mut keys: Vec<&String> = groups.keys().collect();
        keys.sort();
        for k in keys {
            let g = &groups[k];
            let mut roots: Vec<u64> = g
                .get("root_ids")
                .and_then(|v| v.as_array())
                .map(|a| a.iter().filter_map(|x| x.as_u64()).collect())
                .unwrap_or_default();
            roots.sort_unstable();
            roots.dedup();
            let idx = c.indices_of_sorted(&roots);
            by_name.insert(k.clone(), names.len());
            names.push(k.clone());
            members.push(idx);
        }

        // Food-odour channels, grouped per glomerulus and response band.
        let mut odor_channels = Vec::new();
        if let Some(ch) = root
            .get("food_olfaction")
            .and_then(|f| f.get("channels"))
            .and_then(|v| v.as_object())
        {
            let mut cks: Vec<&String> = ch.keys().collect();
            cks.sort();
            for ck in cks {
                let v = &ch[ck];
                let mut roots: Vec<u64> = v
                    .get("root_ids")
                    .and_then(|x| x.as_array())
                    .map(|a| a.iter().filter_map(|x| x.as_u64()).collect())
                    .unwrap_or_default();
                roots.sort_unstable();
                roots.dedup();
                let band = v.get("response_band").and_then(|b| b.as_str()).unwrap_or("");
                let glomerulus = v
                    .get("glomerulus")
                    .and_then(|b| b.as_str())
                    .unwrap_or(ck)
                    .to_string();
                let attractive = band == "attractive";
                odor_channels.push((glomerulus, attractive, c.indices_of_sorted(&roots)));
            }
        }

        let n = c.n;
        let mut neuron_group = vec![0u16; n];
        for (gi, mem) in members.iter().enumerate() {
            for &mi in mem {
                // A neuron may appear in several groups; keep the first so the
                // per-step accounting stays a partition.
                if neuron_group[mi as usize] == 0 {
                    neuron_group[mi as usize] = (gi + 1) as u16;
                }
            }
        }
        let group_region: Vec<u8> = names.iter().map(|n| region_of(n)).collect();
        let group_size: Vec<u32> = members.iter().map(|m| m.len().max(1) as u32).collect();
        let group_scale_hz: Vec<f32> = names
            .iter()
            .map(|n| phys_full_scale_hz(n).unwrap_or(0.0))
            .collect();

        Ok(Groups {
            names,
            members,
            by_name,
            neuron_group,
            group_region,
            group_size,
            group_scale_hz,
            odor_channels,
        })
    }

    pub fn io_path() -> PathBuf {
        io_json_path()
    }

    /// The mechanosensory / proprioceptive inventory, which is a separate file
    /// so neither it nor the main I/O set has to know about the other.
    pub fn mechano_path() -> PathBuf {
        std::env::var_os("FLYVERSE_MECHANO_JSON")
            .map(PathBuf::from)
            .unwrap_or_else(|| PathBuf::from("assets/male_cns_v1_mechanosensory_io.json"))
    }

    /// Merge the groups of another neural_io-format file into this set.
    ///
    /// A group name that already exists is replaced; a new one is appended.
    /// The derived tables (`neuron_group`, `group_region`, `group_size`) are
    /// rebuilt afterwards so they stay consistent with `members`, which is
    /// what the per-neuron accounting in the LIF loop depends on.
    pub fn merge_file(&mut self, c: &Connectome, path: &Path) -> Result<usize> {
        if !path.exists() {
            anyhow::bail!("missing group file {}", path.display());
        }
        let text = std::fs::read_to_string(path)
            .with_context(|| format!("read {}", path.display()))?;
        let root: Value = serde_json::from_str(&text)
            .with_context(|| format!("parse {}", path.display()))?;
        let groups = root
            .get("groups")
            .and_then(|v| v.as_object())
            .with_context(|| format!("{} has no groups object", path.display()))?;
        let mut keys: Vec<&String> = groups.keys().collect();
        keys.sort();

        let mut added = 0usize;
        for k in keys {
            let g = &groups[k];
            let mut roots: Vec<u64> = g
                .get("root_ids")
                .and_then(|v| v.as_array())
                .map(|a| a.iter().filter_map(|x| x.as_u64()).collect())
                .unwrap_or_default();
            roots.sort_unstable();
            roots.dedup();
            if roots.is_empty() {
                // A group that selected nothing would silently contribute a
                // dead channel, so refuse it loudly instead.
                anyhow::bail!("group {k} in {} selected no neurons", path.display());
            }
            let idx = c.indices_of_sorted(&roots);
            match self.by_name.get(k) {
                Some(&gi) => self.members[gi] = idx,
                None => {
                    self.by_name.insert(k.clone(), self.names.len());
                    self.names.push(k.clone());
                    self.members.push(idx);
                    added += 1;
                }
            }
        }
        self.rebuild(c.n);
        Ok(added)
    }

    fn rebuild(&mut self, n: usize) {
        let mut neuron_group = vec![0u16; n];
        for (gi, mem) in self.members.iter().enumerate() {
            for &mi in mem {
                if neuron_group[mi as usize] == 0 {
                    neuron_group[mi as usize] = (gi + 1) as u16;
                }
            }
        }
        self.neuron_group = neuron_group;
        self.group_region = self.names.iter().map(|n| region_of(n)).collect();
        self.group_size = self.members.iter().map(|m| m.len().max(1) as u32).collect();
        self.group_scale_hz = self
            .names
            .iter()
            .map(|n| phys_full_scale_hz(n).unwrap_or(0.0))
            .collect();
    }
}

/// Poisson driver over a fixed set of target neurons, with an independent
/// counter-based stream per channel so channels do not share phase.
pub struct Drive {
    pub targets: Vec<u32>,
    pub rate_hz: f64,
    seed: u64,
    step: u64,
    buf: Vec<(u32, u32)>,
}

impl Drive {
    pub fn new(targets: Vec<u32>, rate_hz: f64, seed: u64) -> Drive {
        Drive { targets, rate_hz, seed, step: 0, buf: Vec::with_capacity(64) }
    }

    pub fn empty() -> Drive {
        Drive::new(Vec::new(), 0.0, 0)
    }

    #[inline]
    fn u01(seed: u64, step: u64, j: u64) -> f64 {
        let mut z = seed
            .wrapping_add(step.wrapping_mul(0x9E37_79B9_7F4A_7C15))
            .wrapping_add(j.wrapping_mul(0xBF58_476D_1CE4_E5B9));
        z = (z ^ (z >> 30)).wrapping_mul(0xBF58_476D_1CE4_E5B9);
        z = (z ^ (z >> 27)).wrapping_mul(0x94D0_49BB_1331_11EB);
        z ^= z >> 31;
        (z >> 11) as f64 / (1u64 << 53) as f64
    }

    pub fn events(&mut self) -> &[(u32, u32)] {
        let p = self.rate_hz * DT_MS as f64 / 1000.0;
        self.buf.clear();
        if p > 0.0 && !self.targets.is_empty() {
            for (j, &t) in self.targets.iter().enumerate() {
                if Self::u01(self.seed, self.step, j as u64) < p {
                    self.buf.push((t, 1));
                }
            }
        }
        self.step += 1;
        &self.buf
    }
}

/// Per-group spike accounting refreshed at the control rate.
pub struct GroupRates {
    pub counts: Vec<u32>,
    pub rate_hz: Vec<f32>,
    pub window_steps: u32,
    /// The MEASUREMENT's arithmetic ceiling, `1000 / window_ms` Hz: one spike
    /// per member per window. It is what a spike count over this window can
    /// express, and nothing more. It is the reference for the groups with no
    /// physiological anchor, and for the `analyze/yaw.rs` steering fraction.
    window_hz: f32,
    /// Per-group ACTUATOR full scale, Hz per neuron, refreshed from `Groups` at
    /// every `commit`. For an anchored group this is the physiological maximum
    /// its motor neurons reach (`POWER_MN_MAX_HZ` for the flight-power pools);
    /// for an unanchored one it stays `window_hz`.
    pub scale_hz: Vec<f32>,
    acc: Vec<u32>,
}

impl GroupRates {
    pub fn new(ngroups: usize, window_steps: u32) -> GroupRates {
        let window_hz = 1000.0 / (window_steps as f32 * DT_MS);
        GroupRates {
            counts: vec![0; ngroups],
            rate_hz: vec![0.0; ngroups],
            window_steps,
            window_hz,
            scale_hz: vec![window_hz; ngroups],
            acc: vec![0; ngroups],
        }
    }

    #[inline]
    pub fn observe(&mut self, g: u16) {
        if g != 0 {
            self.acc[(g - 1) as usize] += 1;
        }
    }

    pub fn commit(&mut self, groups: &Groups) {
        let ms = self.window_steps as f32 * DT_MS;
        for i in 0..self.acc.len() {
            self.counts[i] = self.acc[i];
            self.rate_hz[i] = self.acc[i] as f32 / (ms / 1000.0) / groups.group_size[i] as f32;
            // Physiological full scale for this group, or the window's
            // arithmetic ceiling when it has no anchor (0.0 marker).
            let phys = groups.group_scale_hz.get(i).copied().unwrap_or(0.0);
            self.scale_hz[i] = if phys > 0.0 { phys } else { self.window_hz };
            self.acc[i] = 0;
        }
    }

    /// The full scale of the MEASUREMENT, Hz per neuron: `1000 / window_ms`.
    ///
    /// A read-out is a spike COUNT over the control window divided by the
    /// window's duration and the group size (see `commit`). The window is
    /// `window_steps` simulation steps of `DT_MS` ms long, and the LIF
    /// refractory period (`lif::REFRACTORY_MS` = 2.2 ms) is longer than the
    /// 2 ms window, so a member neuron contributes at most ONE spike to a
    /// window. The window therefore holds at most `group_size` spikes, and the
    /// largest per-neuron rate it can represent is `1000 / window_ms` Hz
    /// (500 Hz at this window).
    ///
    /// That ceiling is a property of the measurement, NOT a physiological rate:
    /// no flight motor neuron fires at 500 Hz, and an asynchronous flight power
    /// muscle asks for about 20 Hz at full activation (`POWER_MN_MAX_HZ`).
    /// Do not use this as the actuator's full scale -- `norm` normalises each
    /// group by its own physical full scale for exactly that reason. It remains
    /// the reference for unanchored groups (where it makes `norm` the fraction
    /// of the pool that fired) and for the steering fraction in `analyze/yaw.rs`.
    pub fn full_scale_hz(&self) -> f32 {
        self.window_hz
    }

    /// Fraction of the group's full scale the pool reached in the last control
    /// window, 0..1.
    ///
    /// For an unanchored group the full scale is the measurement ceiling, so
    /// this is the fraction of the pool that fired (the graded spike count
    /// itself: `spikes / group_size`). For an anchored group it is the fraction
    /// of the physiological maximum rate the motor neurons reached, which is
    /// the quantity an actuator can consume: `body.rs` reads the flight-power
    /// value as the muscle activation `a`.
    ///
    /// The `.clamp` below is a numerical guard, not the operating point.
    ///
    /// The first-published form divided the rate by a fixed per-group anchor
    /// (110 Hz for the steering pools, 90 for the wing-power pools, 70 for the
    /// descending ones). Those anchors sat BELOW the rates the pools actually
    /// run at: the steering pools fire 166.7-333.3 Hz, so every nonzero window
    /// already exceeded the 110 Hz anchor by at least 1.5x and the read-out
    /// could only report 0 or 1. The graded count was discarded by the
    /// divisor, before the clamp could even be blamed: a clamp above a signal
    /// that never reaches it is not what destroys the signal.
    pub fn norm(&self, gi: usize) -> f32 {
        if gi == usize::MAX {
            return 0.0;
        }
        let scale = self.scale_hz.get(gi).copied().unwrap_or(self.window_hz);
        (self.rate_hz[gi] / scale).clamp(0.0, 1.0)
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn readout_keeps_the_graded_spike_count() {
        // For a group with no physiological anchor the read-out's full scale is
        // one spike per member per window, so the normalised value IS the
        // fraction of the pool that fired. A pool that fires k of n members must
        // read k/n; the pre-fix code divided by a fixed 110 Hz anchor that the
        // pools' real rates (166.7-333.3 Hz) already exceeded by 1.5x, so every
        // one of these read 1.0. (Anchored groups are covered by
        // `flight_power_readout_is_scaled_by_the_motoneuron_max_rate`.)
        let mut r = GroupRates::new(1, 20); // 20 steps x 0.1 ms = 2 ms window
        let full = r.full_scale_hz();
        assert!((full - 500.0).abs() < 1e-3, "2 ms window ceiling was {full} Hz");

        for (hz, want) in [(166.7f32, 1.0 / 3.0), (250.0, 0.5), (333.3, 2.0 / 3.0)] {
            r.rate_hz[0] = hz;
            let v = r.norm(0);
            assert!(
                (v - want).abs() < 2e-3,
                "{hz} Hz should read {want:.3} (fraction of pool), got {v:.3}"
            );
            assert!(v < 1.0, "{hz} Hz must not saturate the read-out");
        }

        // The ceiling itself reads exactly 1.0, and the guard holds above it.
        r.rate_hz[0] = full;
        assert!((r.norm(0) - 1.0).abs() < 1e-6);
        r.rate_hz[0] = 3.0 * full;
        assert_eq!(r.norm(0), 1.0);
        assert_eq!(r.norm(usize::MAX), 0.0);
    }

    /// A flight-power pool must be measured against the physiological maximum
    /// rate of a DLM/DVM motor neuron, not against the spike-count window's
    /// arithmetic ceiling. 500 Hz is one spike per member per 2 ms window; it is
    /// not a rate any flight muscle can be driven at. See `POWER_MN_MAX_HZ`.
    #[test]
    fn flight_power_readout_is_scaled_by_the_motoneuron_max_rate() {
        assert_eq!(
            phys_full_scale_hz("motor_flight_power_left"),
            Some(POWER_MN_MAX_HZ)
        );
        assert_eq!(
            phys_full_scale_hz("motor_flight_power_right"),
            Some(POWER_MN_MAX_HZ)
        );
        // Only the actuator-driving pools are anchored so far.
        assert_eq!(phys_full_scale_hz("motor_flight_steering_left"), None);

        let mut r = GroupRates::new(1, 20);
        r.scale_hz[0] = POWER_MN_MAX_HZ;
        r.rate_hz[0] = POWER_MN_MAX_HZ;
        assert!((r.norm(0) - 1.0).abs() < 1e-6, "20 Hz/neuron is full activation");
        r.rate_hz[0] = 0.5 * POWER_MN_MAX_HZ;
        assert!((r.norm(0) - 0.5).abs() < 1e-6, "10 Hz/neuron is half activation");
        // The model's own pool rate sits far above the physiological maximum,
        // so the anchored read-out saturates. That is a statement about the
        // network's rate scale, and it is why the anchor alone cannot be a fix.
        r.rate_hz[0] = 333.3;
        assert_eq!(r.norm(0), 1.0);

        // `commit` wires the anchor in from the group names.
        let groups = fake_groups(&["motor_flight_power_left", "motor_flight_steering_left"]);
        let mut r = GroupRates::new(2, 20);
        r.acc[0] = 12; // every power motor neuron fired
        r.acc[1] = 3;
        r.commit(&groups);
        assert!(
            (r.scale_hz[0] - POWER_MN_MAX_HZ).abs() < 1e-6,
            "power pool scale was {}",
            r.scale_hz[0]
        );
        assert!(
            (r.scale_hz[1] - 500.0).abs() < 1e-6,
            "an unanchored group keeps the window ceiling, got {}",
            r.scale_hz[1]
        );
        assert_eq!(r.norm(0), 1.0);
    }

    /// A `Groups` with the named groups and no members, for the read-out tests.
    fn fake_groups(names: &[&str]) -> Groups {
        let names: Vec<String> = names.iter().map(|s| s.to_string()).collect();
        let by_name = names
            .iter()
            .cloned()
            .enumerate()
            .map(|(i, n)| (n, i))
            .collect();
        let members = vec![Vec::new(); names.len()];
        Groups {
            group_region: names.iter().map(|n| region_of(n)).collect(),
            group_size: vec![12, 3],
            group_scale_hz: names
                .iter()
                .map(|n| phys_full_scale_hz(n).unwrap_or(0.0))
                .collect(),
            names,
            members,
            by_name,
            neuron_group: Vec::new(),
            odor_channels: Vec::new(),
        }
    }
}
