//! Neural-I/O groups from the pinned MaleCNS artifact.
//!
//! `assets/neuromechfly/male_cns_v1_neural_io.json` selects annotated
//! populations by cell type from Janelia's own annotation table. Every group
//! resolves to real MaleCNS body IDs, all of which are present in the pack
//! (the artifact reports zero missing roots). Nothing here is fabricated
//! wiring: these are the published motor neurons, descending neurons and
//! sensory receptor populations, used as explicit readout and stimulation
//! interfaces.

use crate::lif::DT_MS;
use crate::pack::Connectome;
use anyhow::{Context, Result};
use serde_json::Value;
use std::collections::HashMap;
use std::path::{Path, PathBuf};

/// Neuron-group annotations shipped with the repo (from the MaleCNS /
/// neuromechanistic-fly release). Override with `FLYVERSE_IO_JSON`.
pub const IO_JSON: &str = "assets/male_cns_v1_neural_io.json";

/// Resolve the group annotation table: `$FLYVERSE_IO_JSON`, else IO_JSON.
pub fn io_json_path() -> PathBuf {
    std::env::var("FLYVERSE_IO_JSON")
        .map(PathBuf::from)
        .unwrap_or_else(|_| PathBuf::from(IO_JSON))
}

/// Physiological FULL-STROKE firing rate of a flight POWER motor neuron, Hz
/// per neuron. This is the denominator that turns the pool's measured firing
/// rate into the actuator command `a` in 0..1 that `body.rs` reads.
///
/// The flight power muscles (DLM/DVM) are *asynchronous* indirect flight
/// muscles: the wingbeat is generated by the thorax's own stretch-activated
/// oscillator at ~200 Hz and is decoupled from the motor-neuron firing rate,
/// which only sets the muscle's activation level. The consequence is that the
/// motor neurons fire far BELOW the wingbeat frequency:
///
/// * Gordon & Dickinson (2006), PNAS 103(11):4311-4315,
///   doi:10.1073/pnas.0510109103: "The motor neurons of the A-IFMs fire at a
///   rate (approximately 5 Hz in *Drosophila*) well below contraction frequency
///   (approximately 200 Hz)"; mechanical power rises and falls with the firing
///   frequency, and the recorded spike frequency went "up to approximately
///   20 Hz" during visually elicited manoeuvres.
/// * Lehmann, Skandalis & Berthe (2013), J. R. Soc. Interface 10:20121050,
///   doi:10.1098/rsif.2012.1050: "the A-IFM's low spike frequency between 5 and
///   20 Hz maintains rather constant intramuscular calcium levels during
///   flight"; power is linear in intramuscular calcium over 20-120 W/kg.
/// * Huerkey, Schueler, Ryglewski, Duch, Schreiber, Silies et al. (2023), "Gap
///   junctions desynchronize a neural circuit to stabilize insect flight",
///   *Nature* 618:118-124, doi:10.1038/s41586-023-06099-0: each of the five
///   identified DLM motor neurons "fires only every approximately 20th to 40th
///   wingbeat" (5-10 Hz at a 200 Hz wingbeat), the tethered-flight working range
///   is "approximately 3-12 Hz" (Fig. 1c), and the measured f-I curve is linear
///   over 3-30 Hz, i.e. tuned to that range.
///
/// **Why 12 Hz, and not the 20 Hz this anchor used to carry.** `a = 1` is the
/// FULL-STROKE endpoint — the spec pins it at `F_lift/(W/2) ~ 1.2`
/// (physical-model-spec.md §6.5, derived from the mandatory self-check in §6.3)
/// — so this constant is the rate at which the muscle reaches maximal
/// activation and the wing its full stroke. The measured in-flight working
/// range tops out at **12 Hz**; the ~20 Hz band is reached only in elicited
/// manoeuvres, and the f-I curve stays linear well past it, so 20 Hz is a
/// manoeuvre excursion rather than the activation ceiling. Putting the
/// full-stroke endpoint at the top of the measured in-flight band keeps the
/// whole normal flight envelope inside the command's graded range; putting it
/// at 20 Hz makes the animal's entire sustained range a fraction of full scale
/// and any manoeuvre saturate. See `POWER_MN_BAND_LO_HZ`,
/// `POWER_MN_BAND_HI_HZ`.
pub const POWER_MN_FULL_STROKE_HZ: f32 = 12.0;

/// The measured in-flight working range of the flight power motor neurons, Hz
/// per neuron. [M] Huerkey et al. 2023, *Nature* 618:118-124, Fig. 1c:
/// "approximately 3-12 Hz"; Gordon & Dickinson 2006 put the sustained value at
/// "approximately 5 Hz". Anything the model reports outside this band is
/// outside the range the animal was measured to fly at.
pub const POWER_MN_BAND_LO_HZ: f32 = 3.0;
pub const POWER_MN_BAND_HI_HZ: f32 = 12.0;

/// The measured MAXIMUM rate a flight power motor neuron reaches, Hz per
/// neuron: the "up to approximately 20 Hz" seen during visually elicited
/// manoeuvres (Gordon & Dickinson 2006), not the ceiling of normal flight. It
/// is reported by `mn-audit` as the manoeuvre band and is deliberately **not**
/// the actuator's full scale — see `POWER_MN_FULL_STROKE_HZ`.
pub const POWER_MN_MANOEUVRE_MAX_HZ: f32 = 20.0;

/// Physiological FULL-SCALE firing rate of a flight STEERING motor neuron, Hz
/// per neuron. This is the denominator that turns a steering pool's measured
/// firing rate into the steering command in 0..1 that `body.rs` reads as the
/// stroke-plane tilt.
///
/// The steering muscles are the exact OPPOSITE case to the flight power
/// muscles, and it is why they must not reuse `POWER_MN_FULL_STROKE_HZ`:
///
/// * The power muscles (DLM/DVM) are *asynchronous* indirect flight muscles.
///   The wingbeat is generated by the thorax's own stretch-activated oscillator
///   at ~200 Hz, and the motor neurons only set the muscle's activation level,
///   so they fire far BELOW the wingbeat — 3-12 Hz (see
///   `POWER_MN_FULL_STROKE_HZ`).
/// * The steering muscles are *synchronous* direct flight muscles. Each is
///   innervated by a SINGLE motor neuron and fires once per wingbeat,
///   phase-locked to the stroke cycle, so their rates run AT the wingbeat
///   frequency — about 200 Hz — an order of magnitude above the power muscles.
///
/// Citations:
/// * Melis, Siwanowicz & Dickinson (2024), "Machine learning reveals the
///   control mechanics of an insect wing hinge", *Nature* **628**(8009):795-803,
///   doi:10.1038/s41586-024-07293-4 — the wing hinge carries 12 control
///   ("steering") muscles, each innervated by a **single motor neuron**; their
///   activity is what regulates stroke amplitude, stroke-plane tilt and flip
///   timing on a cycle-by-cycle basis.
/// * Balint & Dickinson (2001), "The correlation between wing kinematics and
///   steering muscle activity in the blowfly *Calliphora vicina*", *J. Exp.
///   Biol.* **204**:4213-4226 — the direct steering muscle fires **in a
///   one-to-one relationship with the wingbeat** (the reason a wing-beat
///   frequency acoustic recording is a valid proxy for direct-flight-muscle
///   spiking). Same one-to-one statement for *Drosophila* M.b2 in Lehmann &
///   Götz (1996), *J. Comp. Physiol. A* **179**:311-322,
///   doi:10.1007/BF00194985 ("the phase-lock of the spontaneous spikes of the
///   second basalar muscle within the wing beat cycle").
/// * "Synaptic architecture of leg and wing premotor control networks in
///   *Drosophila*" (2024), PMC11356479 — "some wing steering MNs fire tonically
///   during flight **at rates as high as wingbeat frequency (about 200 Hz)**",
///   in contrast to the DLM/DVM MNs at ~6 Hz.
/// * This repo's own `docs/physical-model-spec.md` §2 pins the wingbeat at
///   **f = 200 Hz** and §2 names the steering set as tp1, tp2, hg1-hg4, b1-b3
///   acting as cycle-by-cycle modulators; `docs/haltere-probe.md` and
///   `src/sim.rs` (`MN_CALIBRATED_GROUPS`) already state the steering muscles
///   are synchronous at about one spike per wingbeat.
///
/// The full-scale endpoint is therefore **one spike per wingbeat**: at the
/// spec's 200 Hz wingbeat that is 200 Hz/neuron, and `a = 1` means every
/// steering motor neuron fires on every stroke — full steering authority. This
/// is not a re-tuned scale: it is the same physical quantity the power pools
/// use (the rate at which the muscle reaches its maximum useful activation),
/// measured for a different, synchronous muscle class.
pub const STEER_MN_FULL_SCALE_HZ: f32 = 200.0;

/// Time constant over which a flight POWER pool's firing rate is estimated
/// before it becomes the actuator command, seconds. [M]-anchored.
///
/// The A-IFM reads out the *tonic* motor-neuron rate, not a coincidence inside
/// one 2 ms window: the muscle integrates the arriving spikes over its own
/// transduction time, and those times are measured — DLM fibre action-potential
/// decay tau ~ 14 ms, myoplasmic Ca2+ decay tau ~ 79 ms, wingbeat-change tau
/// ~ 83 ms (Huerkey et al. 2023, *Nature* 618:118-124, Fig. 4b). This uses the
/// calcium decay, the slowest of the three, which is the one the muscle's
/// activation level follows.
///
/// The alternative — estimating the rate from a single 2 ms control window —
/// makes ONE spike read as `1000/2/12 = 41.7` Hz/neuron, several times any
/// rate a flight muscle is asked for. The command then saturates on the first
/// spike of a window and `a` tracks `P(>=1 member fires)`, which is a
/// compressive function of the true rate; no rate-to-force map can recover the
/// measured relation from it.
pub const MOTOR_RATE_TAU_S: f32 = 0.080;

/// The physiological full scale of a read-out, Hz per neuron, or `None` when
/// the group has no physiological anchor.
///
/// `None` groups keep the window's arithmetic ceiling as their reference, which
/// at least leaves the read-out a fraction of the pool in 0..1. Two flight
/// pools are anchored, and they are anchored to two DIFFERENT rates because
/// they are two different muscle classes: the flight-power pools to the
/// asynchronous DLM/DVM in-flight rate (`POWER_MN_FULL_STROKE_HZ`, 12 Hz) and
/// the steering pools to the synchronous one-spike-per-wingbeat rate
/// (`STEER_MN_FULL_SCALE_HZ`, 200 Hz). Both drive an actuator (`body.rs` reads
/// the power value as the muscle activation and the steering values as the
/// stroke-plane tilt), so their scale decides whether the fly can fly and
/// steer, and 500 Hz of motor drive is not a physical quantity either muscle
/// can be asked for. See the two constants for the citations.
pub fn phys_full_scale_hz(name: &str) -> Option<f32> {
    match name {
        "motor_flight_power_left" | "motor_flight_power_right" => Some(POWER_MN_FULL_STROKE_HZ),
        "motor_flight_steering_left" | "motor_flight_steering_right" => {
            Some(STEER_MN_FULL_SCALE_HZ)
        }
        _ => None,
    }
}

/// Region buckets used by the HUD. Order is the wire order.
pub const REGION_NAMES: [&str; 12] = [
    "sensory_leg",
    "olfaction",
    "taste",
    "visual_motion",
    "visual_loom",
    "flight_descending",
    "flight_motor",
    "walking_motor",
    "landing_motor",
    "feeding_motor",
    "central",
    "other",
];

fn region_of(group: &str) -> u8 {
    match group {
        "olfaction_left" | "olfaction_right" => 1,
        "taste_sugar" => 2,
        "visual_motion_left" | "visual_motion_right" => 3,
        "visual_loom_left" | "visual_loom_right" => 4,
        "flight_dng02_left" | "flight_dng02_right" | "flight_dng07_left"
        | "flight_dng07_right" | "flight_state_sapp_left" | "flight_state_sapp_right"
        | "flight_steering_dn_left" | "flight_steering_dn_right" => 5,
        "motor_flight_power_left" | "motor_flight_power_right" | "motor_flight_steering_left"
        | "motor_flight_steering_right" => 6,
        "motor_walking_left" | "motor_walking_right" | "walking_dn_left" | "walking_dn_right" => 7,
        "motor_landing_left" | "motor_landing_right" | "landing_dn_left" | "landing_dn_right" => 8,
        "feeding_mn9" => 9,
        _ => 11,
    }
}

pub struct Groups {
    pub names: Vec<String>,
    pub members: Vec<Vec<u32>>,
    /// name -> group index
    pub by_name: HashMap<String, usize>,
    /// neuron -> group index + 1 (0 means the neuron is in no group)
    pub neuron_group: Vec<u16>,
    /// group -> region bucket
    pub group_region: Vec<u8>,
    /// group -> normalising divisor (member count, at least 1)
    pub group_size: Vec<u32>,
    /// group -> physiological full scale in Hz per neuron, or 0.0 when the group
    /// has no physiological anchor and the window's arithmetic ceiling is used
    /// instead. See `phys_full_scale_hz`.
    pub group_scale_hz: Vec<f32>,
    /// food-odour channels: (glomerulus, attractive?, member indices)
    pub odor_channels: Vec<(String, bool, Vec<u32>)>,
}

impl Groups {
    pub fn get(&self, name: &str) -> &[u32] {
        match self.by_name.get(name) {
            Some(&i) => &self.members[i],
            None => &[],
        }
    }

    pub fn idx(&self, name: &str) -> usize {
        *self.by_name.get(name).unwrap_or(&usize::MAX)
    }

    pub fn load(c: &Connectome, path: &Path) -> Result<Groups> {
        let text = std::fs::read_to_string(path)
            .with_context(|| format!("read {}", path.display()))?;
        let root: Value = serde_json::from_str(&text)?;

        let mut names = Vec::new();
        let mut members: Vec<Vec<u32>> = Vec::new();
        let mut by_name = HashMap::new();

        let groups = root
            .get("groups")
            .and_then(|v| v.as_object())
            .context("neural_io has no groups object")?;
        let mut keys: Vec<&String> = groups.keys().collect();
        keys.sort();
        for k in keys {
            let g = &groups[k];
            let mut roots: Vec<u64> = g
                .get("root_ids")
                .and_then(|v| v.as_array())
                .map(|a| a.iter().filter_map(|x| x.as_u64()).collect())
                .unwrap_or_default();
            roots.sort_unstable();
            roots.dedup();
            let idx = c.indices_of_sorted(&roots);
            by_name.insert(k.clone(), names.len());
            names.push(k.clone());
            members.push(idx);
        }

        // Food-odour channels, grouped per glomerulus and response band.
        let mut odor_channels = Vec::new();
        if let Some(ch) = root
            .get("food_olfaction")
            .and_then(|f| f.get("channels"))
            .and_then(|v| v.as_object())
        {
            let mut cks: Vec<&String> = ch.keys().collect();
            cks.sort();
            for ck in cks {
                let v = &ch[ck];
                let mut roots: Vec<u64> = v
                    .get("root_ids")
                    .and_then(|x| x.as_array())
                    .map(|a| a.iter().filter_map(|x| x.as_u64()).collect())
                    .unwrap_or_default();
                roots.sort_unstable();
                roots.dedup();
                let band = v.get("response_band").and_then(|b| b.as_str()).unwrap_or("");
                let glomerulus = v
                    .get("glomerulus")
                    .and_then(|b| b.as_str())
                    .unwrap_or(ck)
                    .to_string();
                let attractive = band == "attractive";
                odor_channels.push((glomerulus, attractive, c.indices_of_sorted(&roots)));
            }
        }

        let n = c.n;
        let mut neuron_group = vec![0u16; n];
        for (gi, mem) in members.iter().enumerate() {
            for &mi in mem {
                // A neuron may appear in several groups; keep the first so the
                // per-step accounting stays a partition.
                if neuron_group[mi as usize] == 0 {
                    neuron_group[mi as usize] = (gi + 1) as u16;
                }
            }
        }
        let group_region: Vec<u8> = names.iter().map(|n| region_of(n)).collect();
        let group_size: Vec<u32> = members.iter().map(|m| m.len().max(1) as u32).collect();
        let group_scale_hz: Vec<f32> = names
            .iter()
            .map(|n| phys_full_scale_hz(n).unwrap_or(0.0))
            .collect();

        Ok(Groups {
            names,
            members,
            by_name,
            neuron_group,
            group_region,
            group_size,
            group_scale_hz,
            odor_channels,
        })
    }

    pub fn io_path() -> PathBuf {
        io_json_path()
    }

    /// The mechanosensory / proprioceptive inventory, which is a separate file
    /// so neither it nor the main I/O set has to know about the other.
    pub fn mechano_path() -> PathBuf {
        std::env::var_os("FLYVERSE_MECHANO_JSON")
            .map(PathBuf::from)
            .unwrap_or_else(|| PathBuf::from("assets/male_cns_v1_mechanosensory_io.json"))
    }

    /// Merge the groups of another neural_io-format file into this set.
    ///
    /// A group name that already exists is replaced; a new one is appended.
    /// The derived tables (`neuron_group`, `group_region`, `group_size`) are
    /// rebuilt afterwards so they stay consistent with `members`, which is
    /// what the per-neuron accounting in the LIF loop depends on.
    pub fn merge_file(&mut self, c: &Connectome, path: &Path) -> Result<usize> {
        if !path.exists() {
            anyhow::bail!("missing group file {}", path.display());
        }
        let text = std::fs::read_to_string(path)
            .with_context(|| format!("read {}", path.display()))?;
        let root: Value = serde_json::from_str(&text)
            .with_context(|| format!("parse {}", path.display()))?;
        let groups = root
            .get("groups")
            .and_then(|v| v.as_object())
            .with_context(|| format!("{} has no groups object", path.display()))?;
        let mut keys: Vec<&String> = groups.keys().collect();
        keys.sort();

        let mut added = 0usize;
        for k in keys {
            let g = &groups[k];
            let mut roots: Vec<u64> = g
                .get("root_ids")
                .and_then(|v| v.as_array())
                .map(|a| a.iter().filter_map(|x| x.as_u64()).collect())
                .unwrap_or_default();
            roots.sort_unstable();
            roots.dedup();
            if roots.is_empty() {
                // A group that selected nothing would silently contribute a
                // dead channel, so refuse it loudly instead.
                anyhow::bail!("group {k} in {} selected no neurons", path.display());
            }
            let idx = c.indices_of_sorted(&roots);
            match self.by_name.get(k) {
                Some(&gi) => self.members[gi] = idx,
                None => {
                    self.by_name.insert(k.clone(), self.names.len());
                    self.names.push(k.clone());
                    self.members.push(idx);
                    added += 1;
                }
            }
        }
        self.rebuild(c.n);
        Ok(added)
    }

    fn rebuild(&mut self, n: usize) {
        let mut neuron_group = vec![0u16; n];
        for (gi, mem) in self.members.iter().enumerate() {
            for &mi in mem {
                if neuron_group[mi as usize] == 0 {
                    neuron_group[mi as usize] = (gi + 1) as u16;
                }
            }
        }
        self.neuron_group = neuron_group;
        self.group_region = self.names.iter().map(|n| region_of(n)).collect();
        self.group_size = self.members.iter().map(|m| m.len().max(1) as u32).collect();
        self.group_scale_hz = self
            .names
            .iter()
            .map(|n| phys_full_scale_hz(n).unwrap_or(0.0))
            .collect();
    }
}

/// Poisson driver over a fixed set of target neurons, with an independent
/// counter-based stream per channel so channels do not share phase.
pub struct Drive {
    pub targets: Vec<u32>,
    pub rate_hz: f64,
    seed: u64,
    step: u64,
    buf: Vec<(u32, u32)>,
}

impl Drive {
    pub fn new(targets: Vec<u32>, rate_hz: f64, seed: u64) -> Drive {
        Drive { targets, rate_hz, seed, step: 0, buf: Vec::with_capacity(64) }
    }

    pub fn empty() -> Drive {
        Drive::new(Vec::new(), 0.0, 0)
    }

    #[inline]
    fn u01(seed: u64, step: u64, j: u64) -> f64 {
        let mut z = seed
            .wrapping_add(step.wrapping_mul(0x9E37_79B9_7F4A_7C15))
            .wrapping_add(j.wrapping_mul(0xBF58_476D_1CE4_E5B9));
        z = (z ^ (z >> 30)).wrapping_mul(0xBF58_476D_1CE4_E5B9);
        z = (z ^ (z >> 27)).wrapping_mul(0x94D0_49BB_1331_11EB);
        z ^= z >> 31;
        (z >> 11) as f64 / (1u64 << 53) as f64
    }

    pub fn events(&mut self) -> &[(u32, u32)] {
        let p = self.rate_hz * DT_MS as f64 / 1000.0;
        self.buf.clear();
        if p > 0.0 && !self.targets.is_empty() {
            for (j, &t) in self.targets.iter().enumerate() {
                if Self::u01(self.seed, self.step, j as u64) < p {
                    self.buf.push((t, 1));
                }
            }
        }
        self.step += 1;
        &self.buf
    }
}

/// Per-group spike accounting refreshed at the control rate.
pub struct GroupRates {
    pub counts: Vec<u32>,
    pub rate_hz: Vec<f32>,
    pub window_steps: u32,
    /// The MEASUREMENT's arithmetic ceiling, `1000 / window_ms` Hz: one spike
    /// per member per window. It is what a spike count over this window can
    /// express, and nothing more. It is the reference for the groups with no
    /// physiological anchor, and for the `analyze/yaw.rs` steering fraction.
    window_hz: f32,
    /// Per-group ACTUATOR full scale, Hz per neuron, refreshed from `Groups` at
    /// every `commit`. For an anchored group this is the physiological
    /// full-stroke rate its motor neurons reach (`POWER_MN_FULL_STROKE_HZ` for
    /// the flight-power pools); for an unanchored one it stays `window_hz`.
    pub scale_hz: Vec<f32>,
    /// Per-group TONIC rate estimate, Hz per neuron: a first-order lag of
    /// `rate_hz` with time constant `MOTOR_RATE_TAU_S`, refreshed at every
    /// `commit`. Only the anchored groups use it (see `norm`); an unanchored
    /// group keeps `rate_hz` exactly, so its read-out is bit-identical to
    /// before this field existed.
    ///
    /// Why it exists: `rate_hz` is a spike count over one control window, and
    /// for the flight-power pool one spike in a 2 ms window already reads
    /// 41.7 Hz/neuron — above any rate a flight muscle is asked for. The raw
    /// per-window command therefore saturates on the first spike, so `a` is
    /// `~P(>=1 member fires)` and is a compressive function of the pool's true
    /// rate. An actuator that reads out a muscle activation has to average the
    /// arriving spikes over the muscle's own transduction time instead; see
    /// `MOTOR_RATE_TAU_S` for the measured time constants that set it.
    pub smooth_hz: Vec<f32>,
    /// group -> true when the group carries a physiological actuator anchor.
    anchored: Vec<bool>,
    acc: Vec<u32>,
}

impl GroupRates {
    pub fn new(ngroups: usize, window_steps: u32) -> GroupRates {
        let window_hz = 1000.0 / (window_steps as f32 * DT_MS);
        GroupRates {
            counts: vec![0; ngroups],
            rate_hz: vec![0.0; ngroups],
            window_steps,
            window_hz,
            scale_hz: vec![window_hz; ngroups],
            smooth_hz: vec![0.0; ngroups],
            anchored: vec![false; ngroups],
            acc: vec![0; ngroups],
        }
    }

    #[inline]
    pub fn observe(&mut self, g: u16) {
        if g != 0 {
            self.acc[(g - 1) as usize] += 1;
        }
    }

    pub fn commit(&mut self, groups: &Groups) {
        let ms = self.window_steps as f32 * DT_MS;
        let window_s = ms / 1000.0;
        let alpha = 1.0 - (-window_s / MOTOR_RATE_TAU_S).exp();
        for i in 0..self.acc.len() {
            self.counts[i] = self.acc[i];
            self.rate_hz[i] = self.acc[i] as f32 / window_s / groups.group_size[i] as f32;
            // Physiological full scale for this group, or the window's
            // arithmetic ceiling when it has no anchor (0.0 marker).
            let phys = groups.group_scale_hz.get(i).copied().unwrap_or(0.0);
            self.anchored[i] = phys > 0.0;
            self.scale_hz[i] = if phys > 0.0 { phys } else { self.window_hz };
            if phys > 0.0 {
                self.smooth_hz[i] += (self.rate_hz[i] - self.smooth_hz[i]) * alpha;
            } else {
                // No anchor: keep the raw window rate so nothing about this
                // group's read-out changes.
                self.smooth_hz[i] = self.rate_hz[i];
            }
            self.acc[i] = 0;
        }
    }

    /// The full scale of the MEASUREMENT, Hz per neuron: `1000 / window_ms`.
    ///
    /// A read-out is a spike COUNT over the control window divided by the
    /// window's duration and the group size (see `commit`). The window is
    /// `window_steps` simulation steps of `DT_MS` ms long, and the LIF
    /// refractory period (`lif::REFRACTORY_MS` = 2.2 ms) is longer than the
    /// 2 ms window, so a member neuron contributes at most ONE spike to a
    /// window. The window therefore holds at most `group_size` spikes, and the
    /// largest per-neuron rate it can represent is `1000 / window_ms` Hz
    /// (500 Hz at this window).
    ///
    /// That ceiling is a property of the measurement, NOT a physiological rate:
    /// no flight motor neuron fires at 500 Hz, and an asynchronous flight power
    /// muscle asks for about 12 Hz at full stroke (`POWER_MN_FULL_STROKE_HZ`).
    /// Do not use this as the actuator's full scale -- `norm` normalises each
    /// group by its own physical full scale for exactly that reason. It remains
    /// the reference for unanchored groups (where it makes `norm` the fraction
    /// of the pool that fired) and for the steering fraction in `analyze/yaw.rs`.
    pub fn full_scale_hz(&self) -> f32 {
        self.window_hz
    }

    /// Fraction of the group's full scale the pool reached in the last control
    /// window, 0..1.
    ///
    /// For an unanchored group the full scale is the measurement ceiling, so
    /// this is the fraction of the pool that fired (the graded spike count
    /// itself: `spikes / group_size`) and the value is bit-identical to what it
    /// was before the anchored branch existed. For an anchored group it is the
    /// fraction of the physiological full-stroke rate the motor neurons
    /// reached, read through the tonic rate estimate `smooth_hz` — the quantity
    /// an actuator can consume: `body.rs` reads the flight-power value as the
    /// muscle activation `a`, and the amplitude map turns it into stroke
    /// amplitude.
    ///
    /// Why the anchored branch reads `smooth_hz` and not `rate_hz`. `rate_hz`
    /// is one control window's spike count divided by the window, and for the
    /// flight-power pool one spike in a 2 ms window reads 41.7 Hz/neuron. Since
    /// the anchor is now 12 Hz (or was 20), every window containing a single
    /// spike saturates the clamp, and the *mean* of the clamped per-window
    /// value is a compressive function of the pool's true rate
    /// (`1 - (1 - f*window/1000)^12`), not a linear one. A muscle does not read
    /// its motor neurons in 2 ms coincidences; it integrates them over its own
    /// transduction time (`MOTOR_RATE_TAU_S`). Doing the same here makes `a`
    /// linear in the pool's firing rate across the measured band, which is what
    /// lets the amplitude map match the measured rate-to-power relation at all.
    ///
    /// The `.clamp` below is a numerical guard, not the operating point. Its
    /// upper bound is now a real physical statement: `a = 1` is the full-stroke
    /// endpoint, i.e. the top of the measured in-flight band, not a rate the
    /// pool never reaches.
    ///
    /// The first-published form divided the rate by a fixed per-group anchor
    /// (110 Hz for the steering pools, 90 for the wing-power pools, 70 for the
    /// descending ones). Those anchors sat BELOW the rates the pools actually
    /// run at: the steering pools fire 166.7-333.3 Hz, so every nonzero window
    /// already exceeded the 110 Hz anchor by at least 1.5x and the read-out
    /// could only report 0 or 1. The graded count was discarded by the
    /// divisor, before the clamp could even be blamed: a clamp above a signal
    /// that never reaches it is not what destroys the signal.
    pub fn norm(&self, gi: usize) -> f32 {
        if gi == usize::MAX {
            return 0.0;
        }
        let scale = self.scale_hz.get(gi).copied().unwrap_or(self.window_hz);
        let hz = if self.anchored.get(gi).copied().unwrap_or(false) {
            self.smooth_hz.get(gi).copied().unwrap_or(0.0)
        } else {
            self.rate_hz.get(gi).copied().unwrap_or(0.0)
        };
        (hz / scale).clamp(0.0, 1.0)
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn readout_keeps_the_graded_spike_count() {
        // For a group with no physiological anchor the read-out's full scale is
        // one spike per member per window, so the normalised value IS the
        // fraction of the pool that fired. A pool that fires k of n members must
        // read k/n; the pre-fix code divided by a fixed 110 Hz anchor that the
        // pools' real rates (166.7-333.3 Hz) already exceeded by 1.5x, so every
        // one of these read 1.0. (Anchored groups are covered by
        // `flight_power_readout_is_scaled_by_the_motoneuron_max_rate`.)
        let mut r = GroupRates::new(1, 20); // 20 steps x 0.1 ms = 2 ms window
        let full = r.full_scale_hz();
        assert!((full - 500.0).abs() < 1e-3, "2 ms window ceiling was {full} Hz");

        for (hz, want) in [(166.7f32, 1.0 / 3.0), (250.0, 0.5), (333.3, 2.0 / 3.0)] {
            r.rate_hz[0] = hz;
            let v = r.norm(0);
            assert!(
                (v - want).abs() < 2e-3,
                "{hz} Hz should read {want:.3} (fraction of pool), got {v:.3}"
            );
            assert!(v < 1.0, "{hz} Hz must not saturate the read-out");
        }

        // The ceiling itself reads exactly 1.0, and the guard holds above it.
        r.rate_hz[0] = full;
        assert!((r.norm(0) - 1.0).abs() < 1e-6);
        r.rate_hz[0] = 3.0 * full;
        assert_eq!(r.norm(0), 1.0);
        assert_eq!(r.norm(usize::MAX), 0.0);
    }

    /// A flight-power pool must be measured against the physiological rate at
    /// which its muscle reaches FULL STROKE, not against the spike-count
    /// window's arithmetic ceiling. 500 Hz is one spike per member per 2 ms
    /// window; it is not a rate any flight muscle can be driven at. See
    /// `POWER_MN_FULL_STROKE_HZ`.
    ///
    /// The flight-STEERING pools are now anchored too, and to a different rate,
    /// because they are a different muscle class: synchronous, one spike per
    /// wingbeat, ~200 Hz (`STEER_MN_FULL_SCALE_HZ`). This test previously
    /// asserted `phys_full_scale_hz("motor_flight_steering_left") == None` --
    /// i.e. it pinned the diagnosed defect (steering pools left on the window
    /// ceiling so their read-out was the quantised fraction of the pool that
    /// fired) as if it were a property. See `docs/steering-pool-gradedness.md`.
    #[test]
    fn flight_power_readout_is_scaled_by_the_full_stroke_rate() {
        assert_eq!(
            phys_full_scale_hz("motor_flight_power_left"),
            Some(POWER_MN_FULL_STROKE_HZ)
        );
        assert_eq!(
            phys_full_scale_hz("motor_flight_power_right"),
            Some(POWER_MN_FULL_STROKE_HZ)
        );
        // The steering pools carry their OWN anchor, at the synchronous
        // one-spike-per-wingbeat rate -- an order of magnitude above the power
        // anchor, because the muscle class is the opposite case (asynchronous
        // vs synchronous).
        assert_eq!(
            phys_full_scale_hz("motor_flight_steering_left"),
            Some(STEER_MN_FULL_SCALE_HZ)
        );
        assert_eq!(
            phys_full_scale_hz("motor_flight_steering_right"),
            Some(STEER_MN_FULL_SCALE_HZ)
        );
        assert!(
            STEER_MN_FULL_SCALE_HZ > 10.0 * POWER_MN_FULL_STROKE_HZ,
            "the synchronous steering rate must be an order of magnitude above \
             the asynchronous power rate, got steer {STEER_MN_FULL_SCALE_HZ} vs \
             power {POWER_MN_FULL_STROKE_HZ}"
        );
        // The anchor is the top of the measured in-flight band, not the
        // manoeuvre maximum: `a = 1` pins the full-stroke endpoint, and the
        // animal sustains flight up to 12 Hz, not up to 20.
        assert_eq!(POWER_MN_FULL_STROKE_HZ, POWER_MN_BAND_HI_HZ);
        assert!(POWER_MN_FULL_STROKE_HZ < POWER_MN_MANOEUVRE_MAX_HZ);
        assert!(POWER_MN_BAND_LO_HZ < POWER_MN_BAND_HI_HZ);
        // At the spec's wingbeat the steering anchor is exactly one spike per
        // beat; a 180 Hz (low end of the 180-230 Hz wingbeat range) anchor
        // would be a different choice and this pins the one made.
        assert_eq!(STEER_MN_FULL_SCALE_HZ, 200.0);

        let mut r = GroupRates::new(1, 20);
        r.scale_hz[0] = POWER_MN_FULL_STROKE_HZ;
        r.anchored[0] = true;
        r.smooth_hz[0] = POWER_MN_FULL_STROKE_HZ;
        assert!((r.norm(0) - 1.0).abs() < 1e-6, "12 Hz/neuron is full stroke");
        r.smooth_hz[0] = 0.5 * POWER_MN_FULL_STROKE_HZ;
        assert!((r.norm(0) - 0.5).abs() < 1e-6, "6 Hz/neuron is half activation");

        // `commit` wires the anchors in from the group names.
        let groups = fake_groups(&[
            "motor_flight_power_left",
            "motor_flight_steering_left",
            "motor_walking_left",
        ]);
        let mut r = GroupRates::new(3, 20);
        r.acc[0] = 12; // every power motor neuron fired
        r.acc[1] = 3;
        r.acc[2] = 3;
        r.commit(&groups);
        assert!(
            (r.scale_hz[0] - POWER_MN_FULL_STROKE_HZ).abs() < 1e-6,
            "power pool scale was {}",
            r.scale_hz[0]
        );
        assert!(
            (r.scale_hz[1] - STEER_MN_FULL_SCALE_HZ).abs() < 1e-6,
            "steering pool must carry its own anchor, got {}",
            r.scale_hz[1]
        );
        assert!(
            (r.scale_hz[2] - 500.0).abs() < 1e-6,
            "an unanchored group keeps the window ceiling, got {}",
            r.scale_hz[2]
        );
    }

    /// The steering read-out must be LINEAR in the pool's firing rate against
    /// its own one-spike-per-wingbeat anchor, not the quantised fraction of the
    /// pool that fired in one 2 ms window.
    ///
    /// This is the property that makes the steering command GRADED. The old
    /// read-out divided the pool's spike count by the window ceiling, so a
    /// k-of-n pool read exactly k/n -- for the 3-neuron b1-b3 pool that is 4
    /// levels {0, 1/3, 2/3, 1} and the command could not carry a graded
    /// command at all. Against the 200 Hz anchor the same spike train reads the
    /// pool's true rate over the rate the muscle can be asked for.
    #[test]
    fn steering_readout_is_linear_against_the_one_spike_per_wingbeat_anchor() {
        let groups = fake_groups(&["motor_flight_steering_left"]);
        let mut r = GroupRates::new(1, 20);
        // The anchored branch reads the tonic estimate; set it directly.
        r.anchored[0] = true;
        r.scale_hz[0] = STEER_MN_FULL_SCALE_HZ;
        for (hz, want) in [
            (0.0f32, 0.0f32),
            (50.0, 0.25),
            (100.0, 0.5),
            (200.0, 1.0),
            (400.0, 1.0), // above one spike per wingbeat clamps at full authority
        ] {
            r.smooth_hz[0] = hz;
            let got = r.norm(0);
            assert!(
                (got - want).abs() < 1e-6,
                "a steering pool at {hz:.0} Hz/neuron read {got:.3}, expected {want:.3}"
            );
        }
        // A pool at half the anchor is exactly half steering authority, which
        // the old fraction-of-pool read-out could not express (it read 0, 1/3,
        // 2/3 or 1 and nothing between).
        r.smooth_hz[0] = 0.5 * STEER_MN_FULL_SCALE_HZ;
        assert!((r.norm(0) - 0.5).abs() < 1e-6);
        // Commit wires the steering anchor from the group name.
        let mut r = GroupRates::new(1, 20);
        r.acc[0] = 9;
        r.commit(&groups);
        assert!(
            (r.scale_hz[0] - STEER_MN_FULL_SCALE_HZ).abs() < 1e-6,
            "commit did not wire the steering anchor, scale was {}",
            r.scale_hz[0]
        );
        assert!(r.anchored[0], "steering group must be anchored after commit");
    }

    /// A 12-member pool at a mean 12 Hz/neuron with the anchor at 12 Hz is a
    /// full-stroke command; the anchored read-out is LINEAR in the pool rate.
    ///
    /// This is the property the measured rate-to-power relation depends on. The
    /// old read-out did not have it: one spike in the 2 ms window already read
    /// 41.7 Hz/neuron, so it clamped and the committed command tracked
    /// `P(>= 1 member fires)` -- a compressive curve that reads 0.070 at 3 Hz
    /// where a linear command reads 0.250. That factor of 3.6 is a defect in the
    /// read-out, not in the body, and this test is what catches it.
    #[test]
    fn anchored_readout_is_linear_in_the_pool_rate() {
        let n = 12u32;
        let steps = 20u32; // 2 ms control window
        let window_s = steps as f32 * DT_MS / 1000.0;
        for &rate in &[3.0f32, 6.0, 9.0] {
            let p = rate * window_s; // one Bernoulli per member per window
            let mut r = GroupRates::new(1, steps);
            let groups = fake_groups(&["motor_flight_power_left"]);
            let mut seed = 0x243F_6A88_85A3_08D3u64;
            let mut sum = 0.0f64;
            let windows = 40_000;
            for _ in 0..windows {
                let mut count = 0u32;
                for _ in 0..n {
                    seed = seed
                        .wrapping_mul(6364136223846793005)
                        .wrapping_add(1442695040888963407);
                    let u = ((seed >> 11) as f64) / ((1u64 << 53) as f64);
                    if u < p as f64 {
                        count += 1;
                    }
                }
                r.acc[0] = count;
                r.commit(&groups);
                sum += r.norm(0) as f64;
            }
            let got = (sum / windows as f64) as f32;
            let want = rate / POWER_MN_FULL_STROKE_HZ;
            assert!(
                (got - want).abs() < 0.035,
                "a {rate:.0} Hz/neuron pool read {got:.3}; a linear read-out must give \
                 {want:.3} (the compressive per-window read-out gave 0.070 at 3 Hz)"
            );
        }

        // At the anchor itself the command SATURATES: excursions of the tonic
        // rate above the full-stroke rate are clipped, so the mean command just
        // below the rail is expected to sit slightly below 1.0. That is the
        // clamp behaving as a physical full-stroke limit rather than a
        // measurement artefact, and it is the only place the linearity is
        // deliberately broken.
        let rate = POWER_MN_FULL_STROKE_HZ;
        let p = rate * window_s;
        let mut r = GroupRates::new(1, steps);
        let groups = fake_groups(&["motor_flight_power_left"]);
        let mut seed = 0x243F_6A88_85A3_08D3u64;
        let mut sum = 0.0f64;
        let mut at_rail = 0u32;
        let windows = 40_000;
        for _ in 0..windows {
            let mut count = 0u32;
            for _ in 0..n {
                seed = seed
                    .wrapping_mul(6364136223846793005)
                    .wrapping_add(1442695040888963407);
                let u = ((seed >> 11) as f64) / ((1u64 << 53) as f64);
                if u < p as f64 {
                    count += 1;
                }
            }
            r.acc[0] = count;
            r.commit(&groups);
            let a = r.norm(0);
            if a >= 1.0 {
                at_rail += 1;
            }
            sum += a as f64;
        }
        let got = (sum / windows as f64) as f32;
        assert!(
            got > 0.88 && got <= 1.0,
            "a pool at exactly the {rate:.0} Hz anchor read {got:.3}; it must sit just at or \
             below the full-stroke rail"
        );
        assert!(
            at_rail > 0,
            "a pool at exactly the full-stroke rate must spend some windows clipped at the rail"
        );
    }

    /// The other half of the same property: an anchored group's clamped command
    /// must not be the per-window saturation. At a pool rate of 3 Hz exactly one
    /// window in ten contains a spike, so a per-window read-out sees 0.070.
    #[test]
    fn anchored_readout_is_not_the_per_window_occupancy() {
        let steps = 20u32;
        let window_s = steps as f32 * DT_MS / 1000.0;
        let occupancy = 1.0 - (1.0 - 3.0 * window_s).powi(12);
        assert!(
            (occupancy - 0.070).abs() < 0.01,
            "the old per-window read-out at 3 Hz was {occupancy:.3}, expected ~0.070"
        );
        let want = 3.0 / POWER_MN_FULL_STROKE_HZ; // 0.25
        assert!(
            (want - occupancy).abs() > 0.15,
            "the anchored read-out {want:.3} and the per-window occupancy {occupancy:.3} \
             must not be the same quantity"
        );
    }

    /// A `Groups` with the named groups and no members, for the read-out tests.
    /// `group_size` follows the real pool sizes: 12 for a power/walking pool and
    /// 9 for a steering pool (the spec's tp1/tp2/hg1-hg4/b1-b3 set).
    fn fake_groups(names: &[&str]) -> Groups {
        let names: Vec<String> = names.iter().map(|s| s.to_string()).collect();
        let by_name = names
            .iter()
            .cloned()
            .enumerate()
            .map(|(i, n)| (n, i))
            .collect();
        let members = vec![Vec::new(); names.len()];
        let group_size = names
            .iter()
            .map(|n| if n.contains("steering") { 9 } else { 12 })
            .collect();
        Groups {
            group_region: names.iter().map(|n| region_of(n)).collect(),
            group_size,
            group_scale_hz: names
                .iter()
                .map(|n| phys_full_scale_hz(n).unwrap_or(0.0))
                .collect(),
            names,
            members,
            by_name,
            neuron_group: Vec::new(),
            odor_channels: Vec::new(),
        }
    }
}
